### ISSUE TITLE
Will there be a new FDK AAC build for v1.8.2?

### ISSUE THREAD

**Issue by ChaoticHolon** [FT129/Handbrake-and-FFmpeg-with-fdk-aac#4]
Handbrake v1.8.2 came out on August 10, 2024. It has now been out for two months and has some critical fixes. Hopefully you can get this updated ASAP!

**Comment by Jolar** [comment]
Yes, it would be good with an update. I don't think I ever have been affected by bugs (small ones, but still) in the way as I have been with the last few releases, and those are fixed now.
Many thanks in advance! Your work is much appreciated.

**Comment by FT129** [comment]
updated
