### ISSUE TITLE
1.8.2 fdk does not resize correctly

### ISSUE THREAD

**Issue by Jolar** [FT129/Handbrake-and-FFmpeg-with-fdk-aac#5]
The resolution and scale settings doesn't work, videos are not resized. With certain settings including default presets, the display aspect ratio information changes.

Example of how to reproduce: Open a 1920x1080p video and select the preset "Fast 480p30". Open the Preview window and see how the incorrect aspect ratio information makes the video look. Encode preview and examine the results. Video is still 1920x1080p but with an incorrect aspect ratio, 2.107 in my case using Big Buck Bunny (bbb_sunflower_1080p_30fps_normal.mp4).

**Comment by FT129** [comment]
Sorry, I accidentally built 1.7.3 instead of 1.8.2. Please download and replace the old dll with the new one.
