### ISSUE TITLE
1.8.2 with hb.dll becomes 1.7.3

### ISSUE THREAD

**Issue by Nobes2024** [FT129/Handbrake-and-FFmpeg-with-fdk-aac#6]
i think the dll is the wrong 1 for 1.8.2 because as soon as you copy it over handbrake becomes 1.7.3

**Comment by FT129** [comment]
Just noticed that. I may have messed up. Taking the latest release down while I fix it.

**Comment by FT129** [comment]
> i think the dll is the wrong 1 for 1.8.2 because as soon as you copy it over handbrake becomes 1.7.3

fixed, sorry about that
